import type { News } from "./types"
import { Briefcase, Heart, Microscope, Film, Trophy, Globe, Zap, Cpu, Smartphone, Palette, Car, Home } from "lucide-react"

export const newsCategories = [
  {
    id: "Technology",
    name: "Technology",
    icon: Cpu,
    subcategories: [
      { id: "Artificial Intelligence", name: "Artificial Intelligence" },
      { id: "Machine Learning", name: "Machine Learning" },
      { id: "Startups", name: "Startups" },
      { id: "Gadgets", name: "Gadgets" },
      { id: "Software", name: "Software" },
      { id: "Cybersecurity", name: "Cybersecurity" },
      { id: "Blockchain", name: "Blockchain" },
    ],
  },
  {
    id: "Business",
    name: "Business",
    icon: Briefcase,
    subcategories: [
      { id: "Finance", name: "Finance" },
      { id: "Economy", name: "Economy" },
      { id: "Entrepreneurship", name: "Entrepreneurship" },
      { id: "Markets", name: "Markets" },
      { id: "Real Estate", name: "Real Estate" },
      { id: "Careers", name: "Careers" },
    ],
  },
  {
    id: "health",
    name: "Health",
    icon: Heart,
    subcategories: [
      { id: "fitness", name: "Fitness" },
      { id: "nutrition", name: "Nutrition" },
      { id: "mental-health", name: "Mental Health" },
      { id: "medicine", name: "Medicine" },
      { id: "wellness", name: "Wellness" },
      { id: "healthcare", name: "Healthcare" },
    ],
  },
  {
    id: "science",
    name: "Science",
    icon: Microscope,
    subcategories: [
      { id: "space", name: "Space" },
      { id: "environment", name: "Environment" },
      { id: "research", name: "Research" },
      { id: "physics", name: "Physics" },
      { id: "biology", name: "Biology" },
      { id: "chemistry", name: "Chemistry" },
      { id: "climate", name: "Climate" },
    ],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    icon: Film,
    subcategories: [
      { id: "movies", name: "Movies" },
      { id: "music", name: "Music" },
      { id: "celebrity", name: "Celebrity" },
      { id: "tv-shows", name: "TV Shows" },
      { id: "gaming", name: "Gaming" },
      { id: "streaming", name: "Streaming" },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    icon: Trophy,
    subcategories: [
      { id: "football", name: "Football" },
      { id: "basketball", name: "Basketball" },
      { id: "tennis", name: "Tennis" },
      { id: "soccer", name: "Soccer" },
      { id: "olympics", name: "Olympics" },
      { id: "esports", name: "Esports" },
    ],
  },
  {
    id: "world",
    name: "World News",
    icon: Globe,
    subcategories: [
      { id: "politics", name: "Politics" },
      { id: "conflicts", name: "Conflicts" },
      { id: "diplomacy", name: "Diplomacy" },
      { id: "europe", name: "Europe" },
      { id: "asia", name: "Asia" },
      { id: "americas", name: "Americas" },
    ],
  },
  {
    id: "trending",
    name: "Trending",
    icon: Zap,
    subcategories: [
      { id: "viral", name: "Viral Stories" },
      { id: "social-media", name: "Social Media" },
      { id: "popular", name: "Most Read" },
      { id: "breaking", name: "Breaking News" },
      { id: "debates", name: "Current Debates" },
      { id: "fact-checks", name: "Fact Checks" },
    ],
  },
  {
    id: "mobile",
    name: "Mobile",
    icon: Smartphone,
    subcategories: [
      { id: "ios", name: "iOS" },
      { id: "android", name: "Android" },
      { id: "apps", name: "Apps" },
      { id: "mobile-dev", name: "Mobile Development" },
      { id: "5g", name: "5G" },
      { id: "wearables", name: "Wearables" },
    ],
  },
  {
    id: "culture",
    name: "Culture",
    icon: Palette,
    subcategories: [
      { id: "art", name: "Art" },
      { id: "history", name: "History" },
      { id: "literature", name: "Literature" },
      { id: "architecture", name: "Architecture" },
      { id: "festivals", name: "Festivals" },
    ],
  },
  {
    id: "automotive",
    name: "Automotive",
    icon: Car,
    subcategories: [
      { id: "electric-vehicles", name: "Electric Vehicles" },
      { id: "self-driving", name: "Self-Driving Cars" },
      { id: "motorsports", name: "Motorsports" },
      { id: "car-reviews", name: "Car Reviews" },
      { id: "industry-news", name: "Industry News" },
    ],
  },
  {
    id: "lifestyle",
    name: "Lifestyle",
    icon: Home,
    subcategories: [
      { id: "travel", name: "Travel" },
      { id: "food-drink", name: "Food & Drink" },
      { id: "fashion", name: "Fashion" },
      { id: "home-living", name: "Home & Living" },
      { id: "personal-finance", name: "Personal Finance" },
      { id: "relationships", name: "Relationships" },
    ],
  },
]